name: MemTests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
jobs:
  memtest:
    name: MemTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12.5
          cache: pip
      - run: pip install memray
      - run: pip install -r mlids-trainer/requirements.txt
      - run: python -m memray run output=memray_report.bin mlids-trainer/main.py
      - run: python -m memrary stats memray_report.bin --threshold 1MB
        continue-on-error: true
      - if: failure()
        run: echo "Memory usage exceeded 1MB" && exit 1
